export const initialPrograms = [
    {
        id: 1,
        title: 'Advanced React Development',
        category: 'short-course',
        type: 'Technical',
        description: 'Master React with hooks, context, and advanced patterns',
        duration: '8 weeks',
        learners: 45,
        capacity: 50,
        status: 'active',
        startDate: '2024-02-15',
        endDate: '2024-04-05',
        facilitator: 'Sarah Chen',
        price: 299,
        location: 'Online',
        rating: 4.8,
        enrolled: true,
        featured: true,
        tags: ['React', 'Frontend', 'JavaScript']
    },
    {
        id: 2,
        title: 'Learnership Excellence Program',
        category: 'learnership',
        type: 'Management',
        description: 'Develop learnership skills for tech industry leaders',
        duration: '12 weeks',
        learners: 28,
        capacity: 30,
        status: 'active',
        startDate: '2024-03-01',
        endDate: '2024-05-24',
        facilitator: 'Michael Rodriguez',
        price: 499,
        location: 'Hybrid',
        rating: 4.9,
        enrolled: false,
        featured: true,
        tags: ['Learnership', 'Management', 'Soft Skills']
    },
    {
        id: 3,
        title: 'Data Science Internship',
        category: 'internship',
        type: 'Technical',
        description: 'Hands-on data science project with real-world data',
        duration: '16 weeks',
        learners: 15,
        capacity: 20,
        status: 'active',
        startDate: '2024-01-15',
        endDate: '2024-05-05',
        facilitator: 'Dr. Lisa Wang',
        price: 0,
        location: 'On-site',
        rating: 4.7,
        enrolled: true,
        featured: false,
        tags: ['Data Science', 'Python', 'Machine Learning']
    },
    {
        id: 4,
        title: 'UI/UX Design Fundamentals',
        category: 'short-course',
        type: 'Design',
        description: 'Learn user-centered design principles and prototyping',
        duration: '6 weeks',
        learners: 38,
        capacity: 40,
        status: 'upcoming',
        startDate: '2024-04-01',
        endDate: '2024-05-15',
        facilitator: 'Emma Wilson',
        price: 249,
        location: 'Online',
        rating: 4.6,
        enrolled: false,
        featured: false,
        tags: ['UI/UX', 'Design', 'Figma']
    },
    {
        id: 5,
        title: 'Product Management Bootcamp',
        category: 'learnership',
        type: 'Business',
        description: 'Intensive product management training',
        duration: '10 weeks',
        learners: 22,
        capacity: 25,
        status: 'active',
        startDate: '2024-02-01',
        endDate: '2024-04-12',
        facilitator: 'James Brown',
        price: 599,
        location: 'Online',
        rating: 4.9,
        enrolled: false,
        featured: true,
        tags: ['Product', 'Management', 'Strategy']
    },
    {
        id: 6,
        title: 'Software Engineering Internship',
        category: 'internship',
        type: 'Technical',
        description: 'Full-stack development internship with mentorship',
        duration: '20 weeks',
        learners: 18,
        capacity: 20,
        status: 'ongoing',
        startDate: '2024-01-10',
        endDate: '2024-05-30',
        facilitator: 'Alex Johnson',
        price: 0,
        location: 'Remote',
        rating: 4.8,
        enrolled: true,
        featured: true,
        tags: ['Full-stack', 'JavaScript', 'Node.js']
    },
    {
        id: 7,
        title: 'Digital Marketing Strategy',
        category: 'short-course',
        type: 'Marketing',
        description: 'Modern digital marketing techniques and analytics',
        duration: '5 weeks',
        learners: 42,
        capacity: 50,
        status: 'completed',
        startDate: '2023-11-01',
        endDate: '2023-12-06',
        facilitator: 'David Miller',
        price: 199,
        location: 'Online',
        rating: 4.5,
        enrolled: false,
        featured: false,
        tags: ['Marketing', 'SEO', 'Analytics']
    },
    {
        id: 8,
        title: 'Executive Learnership Program',
        category: 'learnership',
        type: 'Executive',
        description: 'Advanced learnership for senior executives',
        duration: '14 weeks',
        learners: 12,
        capacity: 15,
        status: 'upcoming',
        startDate: '2024-05-01',
        endDate: '2024-08-09',
        facilitator: 'Sophia Garcia',
        price: 899,
        location: 'On-site',
        rating: 0,
        enrolled: false,
        featured: true,
        tags: ['Executive', 'Learnership', 'Strategy']
    },
];

export const categories = [
    { id: 'short-course', label: 'Short Course', icon: 'FaBook', color: 'blue' },
    { id: 'learnership', label: 'Learnership', icon: 'FaUserTie', color: 'purple' },
    { id: 'internship', label: 'Internship', icon: 'FaGraduationCap', color: 'green' }
];

export const statuses = [
    { id: 'upcoming', label: 'Upcoming', color: 'warning' },
    { id: 'active', label: 'Active', color: 'success' },
    { id: 'ongoing', label: 'Ongoing', color: 'info' },
    { id: 'completed', label: 'Completed', color: 'secondary' },
    { id: 'draft', label: 'Draft', color: 'light' }
];

export const types = ['Technical', 'Design', 'Business', 'Marketing', 'Management', 'Executive'];
export const locations = ['Online', 'On-site', 'Hybrid', 'Remote'];
export const facilitators = ['Sarah Chen', 'Michael Rodriguez', 'Dr. Lisa Wang', 'Emma Wilson', 'James Brown', 'Alex Johnson', 'David Miller', 'Sophia Garcia'];